twig:
    form_themes: ['bootstrap_4_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        telephone: '02 35 00 00 00'
        fax: '02 35 00 00 00'
        adresse: 'Paris 75 000 - 3 rue des jardins'
        pathDefault: 'http://localhost/projet/public/index.php/'
